version: 3.8

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./app:/service/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: 'postgres:14.8'
    ports:
      - '5432:5432'
    env_file:
      - .env
