version: 3.8

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./app:/service/app

  postgres:
    image: 'postgres:14.8'
    ports:
      - '5432:5432'
    env_file:
      - .env
