version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./app:/service/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: 'postgres:14.8'
    environment:
      - POSTGRES_USER=impact
      - POSTGRES_PASSWORD=hub
      - POSTGRES_DB=booking
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
